export const experiences = [
  {
    role: "Software Developer",
    company: "Alite Projects",
    location: "Vadodara, India",
    duration: "Dec 2025 - Present",
    type: "Full-time",
    logo: "/alite-projects-logo.svg",
    description: [
      "Architect and implement end-to-end platform features, engineering high-throughput backend APIs in Node.js paired with Redis caching, and building sleek React/Next.js frontends.",
      "Develop scalable web architectures using TypeScript, establishing a reusable component library, and optimizing client-side performance.",
      "Design complex third-party API integrations, orchestrating automated workflows with n8n, and managing scalable data models in PostgreSQL and MongoDB.",
    ],
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Node.js",
      "PostgreSQL",
      "Redis",
      "Vite",
      "Tailwind CSS",
      "MUI",
      "n8n",
      "MongoDB",
    ],
  },
  {
    role: "Software Developer",
    company: "Self Employed",
    location: "Vadodara, India",
    duration: "May 2025 - Present",
    type: "Self-employed",
    logo: "/400X400.svg",
    description: [
      "Architect independent high-performance applications using Node.js, FastAPI, MongoDB, Redis, and Docker.",
      "Design modular RESTful architectures implementing Domain-Driven Design (DDD) and clean code methodologies.",
      "Engineered Shortify, a distributed URL shortener utilizing custom SHA-256 base-62 hashing, achieving sub-millisecond redirect lookups via Redis caching.",
      "Developing Tailor Track, a comprehensive SaaS platform optimizing workflow automation for client orders, precise measurements, and real-time inventory tracking.",
      "Devote deep study to scalable system design, asynchronous message queues (BullMQ), containerization, and advanced performance profiling.",
    ],
    technologies: ["Next.js", "TypeScript", "Node.js", "FastAPI", "MongoDB", "Redis", "Docker"],
  },
  {
    role: "Software Developer",
    company: "Algoacharya",
    location: "Ahmedabad, India",
    duration: "Sept 2023 - May 2025",
    type: "Full-time",
    logo: "/algoacharya-logo.webp",
    description: [
      "Co-engineered a high-frequency algorithmic trading platform for the Indian stock market, managing high-throughput real-time financial streams.",
      "Crafted a performant user interface using Next.js, TypeScript, and Tailwind CSS, implementing dark mode support and custom reusable UI component libraries.",
      "Designed and integrated unified GraphQL and REST API layers, successfully reducing client data-fetch latency by 40%.",
      "Partnered with cross-functional product and design teams to deliver low-latency charting tools, trading terminals, and portfolio metrics.",
      "Accelerated full-stack versatility by contributing robust database schemas in PostgreSQL and writing performant backend logic in Python/Django.",
    ],
    technologies: ["Next.js", "TypeScript", "Python", "Django", "PostgreSQL", "GraphQL"],
  },
  {
    role: ".NET Developer Intern",
    company: "Gujarat Informatics Limited (GIL)",
    location: "Gandhinagar, India",
    duration: "Mar 2023 - May 2023",
    type: "Internship",
    logo: "/gil-logo.png",
    description: [
      "Developed secure public-sector web applications leveraging the .NET Core framework and C#.",
      "Optimized relational database schemas and queries in SQL Server, increasing data retrieval speed by 25%.",
      "Implemented secure token-based authentication and designed RESTful endpoints to facilitate seamless data communication.",
    ],
    technologies: [".NET Core", "SQL Server", "REST API", "C#"],
  },
];
